export const SAVE_USER_DATA = 'SAVE_USER-DATA';

export const SAVE_CURRENCY_DATA = 'SAVE_CURRENCY_DATA';
export const REQUEST_CURRENCY_DATA = 'REQUEST_CURRENCY_DATA';
export const RECEIVE_CURRENCY_DATA_FAILURE = 'RECEIVE_CURRENCY_DATA_FAILURE';
export const RECEIVE_CURRENCY_DATA_SUCCESS = 'RECEIVE_CURRENCY_DATA_SUCCESS';
