export const LOGIN = 'LOGIN';
export const REQUEST_EXCHANGE_RATES = 'REQUEST_EXCHANGE_RATES';
export const SET_EXPENSE_SUCCESS = 'SET_EXPENSES_SUCCESS';
export const REQUEST_EXCHANGE_RATES_ERROR = 'REQUEST_EXCHANGE_RATES_ERROR';
