const LOGIN = 'LOGIN';
const SET_CURRENCIES = 'SET_CURRENCIES';
const ADD_EXPENSES = 'ADD_EXPENSES';
const EDIT_EXPENSES = 'EDIT_EXPENSES';

export { LOGIN, SET_CURRENCIES, ADD_EXPENSES, EDIT_EXPENSES };
